name: so33770938_paper_dropdown_menu_selected
environment:
  sdk: ">=1.2.0 <2.0.0"

dependencies:
  polymer: ^1.0.0-rc.2
  polymer_elements: ^1.0.0-rc.2
  reflectable: ^0.3.2
  web_components: ^0.12.0

dev_dependencies:
  test: ^0.12.3

transformers:
- web_components:
    entry_points:
    - web/index.html

- reflectable:
    entry_points:
    - web/index.dart

- test/pub_serve:
    $include: test/**_test{.*,}.dart

- $dart2js:
    minify: true
    $include: '**/*.bootstrap.initialize.dart'
    #$include: "**/*.polymer.bootstrap.dart"

